name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      unitTestPaths: ""

  build:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    permissions:
      contents: write
    with:
      enabledPlatforms: ${{ needs.ci.outputs.enabledPlatforms }}
      buildRunner: true

  release:
    name: CD
    needs:
      - build
    uses: Skycoder42/dart_test_tools/.github/workflows/create-release.yml@main
    permissions:
      contents: write

  aur_deploy:
    name: CD
    needs:
      - release
    if: needs.release.outputs.releaseCreated == 'true'
    uses: Skycoder42/dart_test_tools/.github/workflows/aur.yml@main
    secrets:
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
